MySQL:
  Hostname: localhost
  Username: username
  Password: password
  Database: database

# Node name. Must be alphanumeric. Max 8 characters
NodeName: undefined

# Times between each thread cicle in ms. Can't be less than 50.
DataExchangerThrottleTime: 200

# Time a packet should live by default. In milliseconds. Default: 1 day.
DefaultTTL: 86400000

# List of tags for this server.
Tags:
- default

# Debug mode. Debug messages will be printed on the server console when this is set to true.
Debug: false
